# Generated by Django 3.2.12 on 2022-02-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_user_report_taskuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='taskuser',
            new_name='user',
        ),
    ]
