# Generated by Django 3.2.12 on 2022-02-19 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_taskuser_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_send',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last time report was sent.'),
        ),
    ]
