# Generated by Django 3.2.12 on 2022-02-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_report_last_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='last_send',
        ),
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Last time report was sent.'),
        ),
    ]
