# Generated by Django 3.2.12 on 2022-02-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220219_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(blank=True, default='2022-02-19 19:51:20', help_text='Enter UTC time in HH:MM'),
        ),
    ]
