# Generated by Django 3.2.12 on 2022-04-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20220413_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(blank=True, default='2022-04-13 12:14:00', help_text='Enter UTC time in HH:MM'),
        ),
    ]
