# Generated by Django 3.2.12 on 2022-04-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20220413_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='board',
            new_name='board_box',
        ),
        migrations.AddField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.Task'),
        ),
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(blank=True, default='2022-04-13 12:41:00', help_text='Enter UTC time in HH:MM'),
        ),
    ]
