# Generated by Django 3.2.12 on 2022-04-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20220413_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='board_box',
            new_name='board',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(blank=True, default='2022-04-13 12:46:00', help_text='Enter UTC time in HH:MM'),
        ),
    ]
