# Generated by Django 3.2.12 on 2022-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_report_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='send_time',
            field=models.DateTimeField(blank=True, default='2022-04-19 04:56:00', help_text='Enter UTC time in HH:MM'),
        ),
    ]
